#!/bin/bash

function print_help() {
    echo ""
    echo "Usage: $SCRIPT_NAME proxy-host [options] [[user@]host1:]file1 ... [[user@]host2:]file2"
    echo ""
    echo "    proxy-host    Hostname or IP address of the host to proxy through."
    echo "    options       Any additional options to pass to the SSH command."
    echo "    user          User to authenticate to the remote host with."
    echo "    host1         Hostname or IP address of the source remote host to connect through the proxy to."
    echo "    host2         Hostname or IP address of the target remote host to connect through the proxy to."
    echo "    file1         Source filename."
    echo "    file2         Target filename."
    echo ""
}

SCRIPT_NAME=$(basename $0)

if [ "$#" -lt 2 ]; then
    print_help
    exit 1
fi

PROXY_HOST=$1
REMOTE_CMD="${@:2}"

scp -o ProxyCommand="ssh $PROXY_HOST \"nc %h %p\"" $REMOTE_CMD
