#!/bin/bash

function print_help() {
    echo ""
    echo "Usage: $SCRIPT_NAME proxy-host remote-host [options]"
    echo ""
    echo "    proxy-host    Hostname or IP address of the host to proxy through."
    echo "    remote-host   Hostname or IP address of the remote host to connect through the proxy to."
    echo "    options       Any additional options to pass to the SSH command."
    echo ""
}

SCRIPT_NAME=$(basename $0)

if [ "$#" -lt 2 ]; then
    print_help
    exit 1
fi

PROXY_HOST=$1
REMOTE_CMD="${@:2}"

ssh -o ProxyCommand="ssh -A $PROXY_HOST \"nc %h %p\"" $REMOTE_CMD
