#!/bin/bash

function print_help() {
    echo ""
    echo "Usage: $SCRIPT_NAME proxy-host [options] [user@]hostname [command]"
    echo ""
    echo "    proxy-host    Hostname or IP address of the host to proxy through."
    echo "    options       Any additional options to pass to the SSH command."
    echo "    user          User to authenticate to the remote host with."
    echo "    hostname      Hostname or IP address of the remote host to connect through the proxy to."
    echo "    command       Optional command to run on the remote host."
    echo ""
}

SCRIPT_NAME=$(basename $0)

if [ "$#" -lt 2 ]; then
    print_help
    exit 1
fi

PROXY_HOST=$1
REMOTE_CMD="${@:2}"

ssh -o ProxyCommand="ssh $PROXY_HOST \"nc %h %p\"" $REMOTE_CMD
